-- The governance state the runtime owns: the four stores the trust loop keeps for itself, and the
-- audit chain every decision is written to.
--
-- What is *not* here is the point of the file. No user table, no role table, no menu, no dictionary:
-- the identity layer maps a subject onto a role the deployment already holds (ADR-0004), and the rest
-- of what an enterprise application needs is the host's (ADR-0017 §1.1). What is left is exactly the
-- state that cannot be delegated — a transcript that a conversation id refers to, a confirmation that
-- somebody actually decided, a side effect that can still be revoked, and the chain that ties them
-- together.
--
-- Dialect: H2, which is what a standalone deployment runs. The dialect is the directory, not the file
-- (see KeelBaseMigrationsAutoConfiguration), so this one is never applied to a host's MySQL.
--
-- Flyway records the checksum of every applied migration, so this file is immutable once applied: a
-- change to the schema is a new V<n>__ file.
--
-- The column types are the ones Hibernate maps these Java types to, and `Instant` is the one worth
-- knowing about: it becomes `timestamp(6) with time zone`, not a plain `TIMESTAMP`. Hibernate's schema
-- validation does not insist on the difference, so a plain `TIMESTAMP` starts up clean and then rounds
-- instants through the JVM's zone on the way in and out — a difference that shows up as a flaky
-- comparison against a freshly created row, months later, in an unrelated test. `ddl-auto=validate` is
-- the check that the rest of the file matches the entities; this comment is the part it cannot check.

CREATE TABLE conversation_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    user_id         VARCHAR(255) NOT NULL,
    role            VARCHAR(255) NOT NULL,
    content         VARCHAR(4000) NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE confirmation_requests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token                VARCHAR(255) NOT NULL UNIQUE,
    tool_name            VARCHAR(255) NOT NULL,
    args_json            VARCHAR(4000) NOT NULL,
    operator_id          VARCHAR(255) NOT NULL,
    risk_level           VARCHAR(255) NOT NULL,
    status               VARCHAR(255) NOT NULL,
    result_id            BIGINT,
    decided_at           TIMESTAMP(6) WITH TIME ZONE,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- The execution axis (ADR-0016): a row can be approved and still be running, so when an attempt
    -- claimed it, when one succeeded and why the last one failed are separate from the status.
    execution_claimed_at TIMESTAMP(6) WITH TIME ZONE,
    executed_at          TIMESTAMP(6) WITH TIME ZONE,
    execution_error      VARCHAR(1000)
);

CREATE TABLE side_effects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    user_id         VARCHAR(255) NOT NULL,
    tool_name       VARCHAR(255) NOT NULL,
    result_type     VARCHAR(255) NOT NULL,
    result_id       BIGINT       NOT NULL,
    revoke_class    VARCHAR(255) NOT NULL,
    revoke_status   VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    args_hash       VARCHAR(255) NOT NULL
);

-- No identity column: the chain head is one row with a fixed id, held under a row lock for the whole
-- of an appending transaction. The row is inserted by AuditChainHeadInitializer at startup, not here —
-- a migration that seeded it would be a second place that decides when the chain exists.
CREATE TABLE audit_chain_head (
    id BIGINT PRIMARY KEY
);

CREATE TABLE ai_audit_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action     VARCHAR(255)  NOT NULL,
    user_id    VARCHAR(255)  NOT NULL,
    detail     VARCHAR(2000) NOT NULL,
    prev_hash  VARCHAR(255),
    hash       VARCHAR(255)  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
