-- The sample business module's tables: the customers the reference tools read, and the follow-up notes
-- they write. It rides in the core because the core is what ships the tools and the endpoints that use
-- it, and a validation of the schema checks every mapped entity — including these two.
--
-- They are separated from V1 on purpose, and the separation is a statement rather than a filing choice:
-- these are not governance state. A customer table is the kind of thing a host already has, and the
-- embedding rule is that whatever the host has, the host keeps (ADR-0017 §1.1). Whether this sample
-- module should be separable from the embeddable core — a deployment that wants the trust loop without
-- the sample CRM — is a live question the migrations make visible instead of hiding.
--
-- Dialect: H2, as in V1. Immutable once applied; changes are new versions.

CREATE TABLE customers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    -- low | medium | high.
    level         VARCHAR(255) NOT NULL,
    owner_user_id VARCHAR(255) NOT NULL,
    -- The row range facts: a range may name an organization or a department, so a row needs both or
    -- neither. Nullable, and null tightens to the owner rather than widening.
    org_id        BIGINT,
    dept_id       BIGINT
);

CREATE TABLE follow_ups (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT       NOT NULL,
    note          VARCHAR(255) NOT NULL,
    due_date      VARCHAR(255),
    owner_user_id VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- Soft delete: revoking this write is a local compensation, so the row stays and is marked.
    deleted_at    TIMESTAMP(6) WITH TIME ZONE
);
