-- The pre-execution write claim: the row that makes two identical calls not both write (seam S11).
--
-- The ledger's key is content-derived and its row is written *after* the tool runs, which is enough for
-- a sequential repeat — the engine asks the ledger first — and not enough for two calls at the same
-- instant: both ask, both find nothing, both write, and the ledger then resolves the duplicate *record*
-- while the second write has already happened and can never be revoked.
--
-- So the arbitration is a row whose unique key is taken *before* execution. `status` is the protocol:
-- `claimed` (an execution is in flight, or died without releasing — indistinguishable, so neither is
-- retried), `settled` (its effect is recorded, `effect_id` names it), `released` (the attempt failed in
-- a way that proves nothing landed, so a retry may re-claim). The key is the same content-derived one
-- the effect uses, because the claim and the effect describe the same call.
--
-- Dialect: H2, as in V1. Immutable once applied; changes are new versions.
--
-- 执行前的写占位：让两次相同调用不会都写的那一行（缝 S11）。
--
-- 账本的键由内容推导、行是工具跑完**之后**才写的：这对**顺序**重复够用（引擎会先问账本），对**同一瞬间**的
-- 两次调用不够——两边都问、都没查到、都写，随后账本裁决的是**记录**那一半，而第二次写已经发生、永远撤不掉。
--
-- 于是仲裁变成**执行前**取一个唯一键的行。`status` 即协议：`claimed`（执行在飞，或死得没释放——两者不可区分，
-- 故都不重试）、`settled`（它的 effect 已登记，`effect_id` 指出是哪一个）、`released`（这次尝试以「证明什么都没
-- 落地」的方式失败，故重试可重新占位）。键与 effect 用的是同一个内容推导键，因为占位与 effect 描述的是同一次调用。
--
-- 方言：H2，与 V1 相同。一经应用即不可改；变更走新版本。
CREATE TABLE write_claims (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    user_id         VARCHAR(255) NOT NULL,
    tool_name       VARCHAR(255) NOT NULL,
    status          VARCHAR(255) NOT NULL,
    effect_id       BIGINT,
    claimed_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    settled_at      TIMESTAMP(6) WITH TIME ZONE
);
