-- The governance state the runtime owns: the four stores the trust loop keeps for itself, and the
-- audit chain every decision is written to. MySQL translation of the h2 sibling — same tables, same
-- columns, same order, different dialect.
--
-- What is *not* here is the point of the file. No user table, no role table, no menu, no dictionary:
-- the identity layer maps a subject onto a role the deployment already holds (ADR-0004), and the rest
-- of what an enterprise application needs is the host's (ADR-0017 §1.1). What is left is exactly the
-- state that cannot be delegated — a transcript that a conversation id refers to, a confirmation that
-- somebody actually decided, a side effect that can still be revoked, and the chain that ties them
-- together.
--
-- Dialect: MySQL, which is what this host runs. The dialect is the directory, not the file (see
-- KeelBaseMigrationsAutoConfiguration), so the h2 sibling is never applied here and this one is never
-- applied to a standalone deployment.
--
-- The two type differences from the h2 sibling, both forced by the dialect rather than chosen:
--   * `GENERATED BY DEFAULT AS IDENTITY` becomes `AUTO_INCREMENT`, MySQL having no standard identity
--     clause.
--   * `TIMESTAMP(6) WITH TIME ZONE` becomes `DATETIME(6)`. Hibernate maps `Instant` to MySQL's
--     `datetime(6)` — MySQL's own `TIMESTAMP` is not the equivalent: it is stored as UTC and converted
--     through the session zone, and it runs out in 2038. The h2 file's warning about rounding instants
--     through a zone applies here with a different outcome: get this wrong and validation still passes
--     while the value shifts.
--
-- Flyway records the checksum of every applied migration, so this file is immutable once applied: a
-- change to the schema is a new V<n>__ file.
--
-- 运行时自己持有的治理状态：信任闭环为自己保留的四个存储，以及每个决定都写入其中的审计链。这是 h2
-- 同族文件的 MySQL 译本——同样的表、同样的列、同样的顺序，只是方言不同。
--
-- **不在**这里的部分才是这个文件的意义。没有用户表、没有角色表、没有菜单、没有字典：身份层把主体映射
-- 到部署方**已经持有的**角色上（ADR-0004），企业应用需要的其余东西是宿主的（ADR-0017 §1.1）。剩下的
-- 正好是**无法委派**的状态——一个会话 id 所指的对话记录、一个真的被人裁决过的确认、一个仍可撤销的
-- 副作用，以及把它们串起来的那条链。
--
-- 方言：MySQL，也就是这个宿主所跑的。方言是**目录**而不是文件（见 KeelBaseMigrationsAutoConfiguration），
-- 故 h2 同族文件在这里不会被应用、本文件也不会被用到独立部署上。
--
-- 与 h2 同族文件的两处类型差异，都是方言逼出来的、不是选的：
--   * `GENERATED BY DEFAULT AS IDENTITY` 变成 `AUTO_INCREMENT`——MySQL 没有标准 identity 子句。
--   * `TIMESTAMP(6) WITH TIME ZONE` 变成 `DATETIME(6)`。Hibernate 把 `Instant` 映射到 MySQL 的
--     `datetime(6)`——MySQL 自己的 `TIMESTAMP` **不是**等价物：它按 UTC 存储并经过会话时区转换，
--     而且 2038 年就到头了。h2 文件里关于「瞬时值被时区四舍五入」的警告在这里后果不同：弄错了
--     校验照样通过，值却会偏移。
--
-- Flyway 会记录每个已应用迁移的校验和，故本文件一旦应用即**不可变**：改 schema 就新开一个 V<n>__ 文件。

CREATE TABLE conversation_messages (
    id              BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    user_id         VARCHAR(255) NOT NULL,
    role            VARCHAR(255) NOT NULL,
    content         VARCHAR(4000) NOT NULL,
    created_at      DATETIME(6) NOT NULL
);

CREATE TABLE confirmation_requests (
    id                   BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    token                VARCHAR(255) NOT NULL UNIQUE,
    tool_name            VARCHAR(255) NOT NULL,
    args_json            VARCHAR(4000) NOT NULL,
    operator_id          VARCHAR(255) NOT NULL,
    risk_level           VARCHAR(255) NOT NULL,
    status               VARCHAR(255) NOT NULL,
    result_id            BIGINT,
    decided_at           DATETIME(6),
    created_at           DATETIME(6) NOT NULL,
    -- The execution axis (ADR-0016): a row can be approved and still be running, so when an attempt
    -- claimed it, when one succeeded and why the last one failed are separate from the status.
    execution_claimed_at DATETIME(6),
    executed_at          DATETIME(6),
    execution_error      VARCHAR(1000)
);

CREATE TABLE side_effects (
    id              BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    user_id         VARCHAR(255) NOT NULL,
    tool_name       VARCHAR(255) NOT NULL,
    result_type     VARCHAR(255) NOT NULL,
    result_id       BIGINT       NOT NULL,
    revoke_class    VARCHAR(255) NOT NULL,
    revoke_status   VARCHAR(255) NOT NULL,
    created_at      DATETIME(6) NOT NULL,
    args_hash       VARCHAR(255) NOT NULL
);

-- No identity column: the chain head is one row with a fixed id, held under a row lock for the whole
-- of an appending transaction. The row is inserted by AuditChainHeadInitializer at startup, not here —
-- a migration that seeded it would be a second place that decides when the chain exists.
CREATE TABLE audit_chain_head (
    id BIGINT PRIMARY KEY
);

CREATE TABLE ai_audit_logs (
    id         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    action     VARCHAR(255)  NOT NULL,
    user_id    VARCHAR(255)  NOT NULL,
    detail     VARCHAR(2000) NOT NULL,
    prev_hash  VARCHAR(255),
    hash       VARCHAR(255)  NOT NULL,
    created_at DATETIME(6) NOT NULL
);
