-- MySQL translation of the h2 sibling — same columns, same order, different dialect.
--
-- The pre-execution write claim: the row that makes two identical calls not both write (seam S11).
--
-- The ledger's key is content-derived and its row is written *after* the tool runs, which is enough for
-- a sequential repeat — the engine asks the ledger first — and not enough for two calls at the same
-- instant: both ask, both find nothing, both write, and the ledger then resolves the duplicate *record*
-- while the second write has already happened and can never be revoked.
--
-- So the arbitration is a row whose unique key is taken *before* execution. `status` is the protocol:
-- `claimed` (an execution is in flight, or died without releasing — indistinguishable, so neither is
-- retried), `settled` (its effect is recorded, `effect_id` names it), `released` (the attempt failed in
-- a way that proves nothing landed, so a retry may re-claim). The key is the same content-derived one
-- the effect uses, because the claim and the effect describe the same call.
--
-- The two type differences from the h2 sibling, both forced by the dialect: `GENERATED BY DEFAULT AS
-- IDENTITY` becomes `AUTO_INCREMENT`, and `TIMESTAMP(6) WITH TIME ZONE` becomes `DATETIME(6)` —
-- Hibernate maps `Instant` to MySQL's `datetime(6)`, not to its own `TIMESTAMP`.
--
-- Flyway records the checksum of every applied migration, so this file is immutable once applied: a
-- change to the schema is a new V<n>__ file.
--
-- 运行时自有 schema 的 MySQL 译本——h2 同族文件：同样的表、同样的列、同样的顺序，只是方言不同。
--
-- 执行前的写占位：让两次相同调用不会都写的那一行（缝 S11）。键由内容推导、effect 行是工具跑完**之后**写的——
-- 这对顺序重复够用，对同一瞬间的两次调用不够。故仲裁改为**执行前**取唯一键的一行；`status` 是协议
-- （`claimed` / `settled` / `released`）。
--
-- 与 h2 同族文件的两处类型差异，都是方言逼出来的：`GENERATED BY DEFAULT AS IDENTITY` → `AUTO_INCREMENT`，
-- `TIMESTAMP(6) WITH TIME ZONE` → `DATETIME(6)`。
--
-- 一经应用即不可改：schema 变更一律新的 V<n>__ 文件。
CREATE TABLE write_claims (
    id              BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    user_id         VARCHAR(255) NOT NULL,
    tool_name       VARCHAR(255) NOT NULL,
    status          VARCHAR(255) NOT NULL,
    effect_id       BIGINT,
    claimed_at      DATETIME(6)  NOT NULL,
    settled_at      DATETIME(6)
);
