-- The sample business module's tables: the customers the reference tools read, and the follow-up notes
-- they write. It rides in the core because the core is what ships the tools and the endpoints that use
-- it, and a validation of the schema checks every mapped entity — including these two.
--
-- They are separated from V1 on purpose, and the separation is a statement rather than a filing choice:
-- these are not governance state. A customer table is the kind of thing a host already has, and the
-- embedding rule is that whatever the host has, the host keeps (ADR-0017 §1.1). Whether this sample
-- module should be separable from the embeddable core — a deployment that wants the trust loop without
-- the sample CRM — is a live question the migrations make visible instead of hiding.
--
-- Dialect: PostgreSQL, as in V1 — the DDL is the h2 sibling's, unchanged. Immutable once applied;
-- changes are new versions.

-- 示例业务模块的两张表：参照工具读的客户，以及它们写的跟进记录。它随核心一起走，因为工具与使用它们的端点
-- 都由核心提供，而 schema 校验会检查**每一个**被映射的实体——包括这两张。
--
-- 与 V1 分开是**有意的**，而且这个分开是一个陈述、不是归档习惯：这些**不是治理状态**。客户表是宿主多半
-- 自己已经有的那类东西，而嵌入的规矩是「宿主已经做了的，归宿主」（ADR-0017 §1.1）。**这个示例模块该不该
-- 从可嵌入核心里摘出去**——让只想要信任闭环、不想要示例 CRM 的部署能取前者——是一个尚未裁决的问题，而迁移
-- 让它**显形**，而不是把它藏起来。
--
-- 方言：PostgreSQL，与 V1 相同 —— DDL 就是 h2 那份、一字未改。一旦应用即不可改；变更走新版本。

CREATE TABLE customers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    -- low | medium | high.
    level         VARCHAR(255) NOT NULL,
    owner_user_id VARCHAR(255) NOT NULL,
    -- The row range facts: a range may name an organization or a department, so a row needs both or
    -- neither. Nullable, and null tightens to the owner rather than widening.
    org_id        BIGINT,
    dept_id       BIGINT
);

CREATE TABLE follow_ups (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT       NOT NULL,
    note          VARCHAR(255) NOT NULL,
    due_date      VARCHAR(255),
    owner_user_id VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- Soft delete: revoking this write is a local compensation, so the row stays and is marked.
    deleted_at    TIMESTAMP(6) WITH TIME ZONE
);
